### PR TITLE
Create subdirectory for plugins. Add metadata to Binja plugin

### PR DESCRIPTION
**Pull request by ZetaTwo**

### CODE REVIEW

**Comment by felixwilhelm** [comment]
Hey,
what's missing before this can be merged?

**Comment by ZetaTwo** [comment]
I need to add some description to the README and then somehow actually test that the plugin metadata is correct. Although I don't even know if that's possible.

**Comment by ZetaTwo** [comment]
I think you should b e able to merge this now.

**Comment by felixwilhelm** [comment]
Thank you! :)

**Pull request merged**
